### ISSUE TITLE
Cancer networks protocol stalls in Binder

### ISSUE THREAD

**Issue by khanspers** [cytoscape/cytoscape-automation#49]
Everything works fine until line 166 (createSubNetworks) where it stalls. Eventually has to be stopped manually. There is no error message. 

https://github.com/cytoscape/cytoscape-automation/blob/master/for-scripters/R/notebooks/Cancer-networks-and-data.Rmd

**Comment by AlexanderPico** [comment]
I suspect this one is due to the 1-2GB RAM max of the publicly-hosted, free version of Binder. We could test with our own hosted instance at NRNB (eventually).  

We could also test by only loading one of the two networks in this protocol and skipping other steps, etc to see if we can get further into the protocol. This would help distinguish a bug at that particular step vs a memory limit.  @khanspers can you try this?
